package net.cyberpunk042.growth.scheduler;

public enum GrowthField {
	GROWTH_ENABLED(Type.BOOLEAN),
	RATE_TICKS(Type.INT),
	RATE_SCALE(Type.DOUBLE),
	START_SCALE(Type.DOUBLE),
	TARGET_SCALE(Type.DOUBLE),
	MIN_SCALE(Type.DOUBLE),
	MAX_SCALE(Type.DOUBLE),
	HAS_COLLISION(Type.BOOLEAN),
	DOES_DESTRUCTION(Type.BOOLEAN),
	HAS_FUSE(Type.BOOLEAN),
	TOUCH_DAMAGE(Type.DOUBLE),
	GROWTH_PROFILE(Type.IDENTIFIER),
	GLOW_PROFILE(Type.IDENTIFIER),
	PARTICLE_PROFILE(Type.IDENTIFIER),
	FIELD_PROFILE(Type.IDENTIFIER),
	PULL_PROFILE(Type.IDENTIFIER),
	PUSH_PROFILE(Type.IDENTIFIER),
	FUSE_PROFILE(Type.IDENTIFIER),
	EXPLOSION_PROFILE(Type.IDENTIFIER),
	OPACITY_PROFILE(Type.IDENTIFIER),
	SPIN_PROFILE(Type.IDENTIFIER),
	WOBBLE_PROFILE(Type.IDENTIFIER),
	PALETTE(Type.IDENTIFIER);

	public enum Type {
		BOOLEAN,
		INT,
		DOUBLE,
		IDENTIFIER
	}

	private final Type type;

	GrowthField(Type type) {
		this.type = type;
	}

	public Type type() {
		return type;
	}
}

